STARTING_DEPTH = 0

CLASS__RANGE_NUM = 2

TIMER_NUM = 3

SEC_LEVEL_NUM = 3

LOOT_TYPE_NUM = 2

CLASS_ZERO_TEXT = "Unknown"

UNKNOWN_CLASS_INT = 0

CLASS_COMBOBOX_VALUES = [
    CLASS_ZERO_TEXT,
    1,2,3,4,5,6
]

NEW_SIG_COMBOBOX_VALUES = [
    "Wormhole",
    "Exit Wormhole",
    "Scan Site"
]

NEW_SIGNATURE_BUTTON_TEXT = "New sig"

DESTINATION_LABEL_TEXT = "Destination"

CLASS_LABEL_TEXT = "Class"

LONG_TIMER_LABEL_TEXT = "24hr"
MID_TIMER_LABEL_TEXT = "24-4hr"
SHORT_TIMER_LABEL_TEXT = "4hr"

HIGH_SEC_LABEL_TEXT = "High Sec"
LOW_SEC_LABEL_TEXT = "Low Sec"
NULL_SEC_LABEL_TEXT = "Null sec"

SCAN_SITE_LABEL_TEXT = "Site"

DATA_LABEL_TEXT = "Relic"
RELIC_LABEL_TEXT = "Data"

JUMP_BUTTON_TEXT = "Jump"

DEFAULT_DESTINATION_CLASS_LABEL_TEXT = "Unknown"

DEFAULT_EXIT_DESTINATION_TEXT = "Unknown"